### ISSUE TITLE
[FIXED] Compiling in Linux doesn't work

### ISSUE THREAD

**Issue by OxygenLack** [iomatix/Lugormod-X#2]
First of all thanks for your improved Lugormod :)

But I encountered a problem with compiling in linux (Kernel 4.15.0-45-generic Ubuntu):

```
 Lmd_Prof_Merc.c:35:24: error: pasting "." and "hp_maxs" does not give a valid preprocessing token
     return data->skills.##name; \
                        ^
Lmd_Prof_Merc.c:60:32: note: in expansion of macro ‘STD_SKILLS_GET’
 #define STD_SKILLS_FUNCS(name) STD_SKILLS_GET(name) \
                                ^
Lmd_Prof_Merc.c:149:1: note: in expansion of macro ‘STD_SKILLS_FUNCS’
 STD_SKILLS_FUNCS(hp_maxs)
 ^
compilation terminated due to -Wfatal-errors.
Makefile:184: recipe for target 'Lmd_Prof_Merc.o' failed
make: *** [Lmd_Prof_Merc.o] Error 1
```

Compiling in Visual Studio 13 worked out great but I'ld like to run this fantastic mod in Linux so it can run 24/7 on my server/nas

Compiling the original Lugormod of "dydzio0614" in linux worked too. 

I tried to copy the "Lmd_Prof_Merc.c" from dydzio0614 to the game directory.. compiling worked but the server wouldnt start of course.

I hope you'll find some spare time to help me out. Thanks a lot for your mod expansion pack

**Comment by OxygenLack** [comment]
Okey... I somehow found solution  but I don't know if it broke something.
Here's what I did ( read on https://stackoverflow.com/questions/13216423/error-pasting-and-red-does-not-give-a-valid-preprocessing-token)

I just removed the # in between the skills.##name

Now it just works...

**Comment by iomatix** [comment]
Great! 
Thanks for your kind words ^ ^
Is it okay until now? 
Anyway I think you've found a little bug inside the code 👍 when I'll get new PC machine I will fix it. 

If everything is working now I close the ticket.

**Comment by OxygenLack** [comment]
Yes it works until now 👍 You can close the Ticket
